export const CHECKOUT_TEXT = {
  ja: {
    title: '購入確認',
    selectedPlan: '選択プラン',
    price: '料金',
    monthlyCredit: '月次Credit',
    renewalCycle: '更新周期',
    renewalValue: '月次',
    paymentProvider: '決済',
    paymentProviderValue: 'Square Hosted Checkout',
    contractTitle: '契約・決済条件',
    cancellationRefund: '解約・返金',
    cancellationRefundValue: '適用条件は利用規約・特定商取引法表記に従います。決済前に下記の法務文書を確認してください。',
    paymentData: '決済情報',
    paymentDataValue: 'カード等の決済情報はSquareで処理されます。AsteraはSquareが保持する決済Customer個人情報を法務表示目的で複製しません。',
    dataRetention: 'Data保持',
    dataRetentionValue: 'Account・Billing・Credit等のDataは用途ごとに保持根拠と期間を分離して管理します。詳細はPrivacy Policyで確認してください。',
    terms: '利用規約',
    privacy: 'Privacy Policy',
    commercial: '特定商取引法表記',
    agreement: '料金、Credit、更新周期、契約・法務条件を確認しました',
    pay: 'Squareで支払う',
    preparing: 'Checkoutを準備中…',
    backPlanCredit: 'プラン / クレジットへ戻る',
    backPricing: '料金Pageへ戻る',
    backApp: 'Appへ戻る',
    connectionChecking: '決済接続を確認しています…',
    connectionReady: '決済接続を確認しました。',
    connectionBlocked: '現在Squareへ進めません。決済接続を再確認してください。',
    loginRequired: '決済へ進むにはLoginが必要です。',
    login: 'Login',
    register: 'Account登録',
    retry: '再確認',
    invalidPlan: '選択Planを確認できません。',
  },
  en: {
    title: 'Purchase confirmation',
    selectedPlan: 'Selected plan',
    price: 'Price',
    monthlyCredit: 'Monthly credit',
    renewalCycle: 'Billing cycle',
    renewalValue: 'Monthly',
    paymentProvider: 'Payment',
    paymentProviderValue: 'Square Hosted Checkout',
    contractTitle: 'Contract and payment terms',
    cancellationRefund: 'Cancellation and refunds',
    cancellationRefundValue: 'Applicable terms follow the Terms of Use and Commercial Transaction Disclosure. Review the legal documents below before payment.',
    paymentData: 'Payment data',
    paymentDataValue: 'Card and payment data are processed by Square. Astera does not duplicate Square-held customer payment information merely for legal display.',
    dataRetention: 'Data retention',
    dataRetentionValue: 'Account, billing and credit data are managed with separate retention grounds and periods by purpose. See the Privacy Policy for details.',
    terms: 'Terms of Use',
    privacy: 'Privacy Policy',
    commercial: 'Commercial Transaction Disclosure',
    agreement: 'I reviewed the price, credit, billing cycle, contract and legal terms',
    pay: 'Pay with Square',
    preparing: 'Preparing Checkout…',
    backPlanCredit: 'Back to Plan / Credit',
    backPricing: 'Back to pricing',
    backApp: 'Back to App',
    connectionChecking: 'Checking payment connection…',
    connectionReady: 'Payment connection verified.',
    connectionBlocked: 'Square Checkout is currently unavailable. Check the payment connection again.',
    loginRequired: 'Login is required before payment.',
    login: 'Login',
    register: 'Create account',
    retry: 'Retry',
    invalidPlan: 'The selected plan could not be confirmed.',
  },
} as const;
