import type { D1Database } from './_account-projection';
import { RESULT_SECTION_KEYS, type NormalizedResultSection } from './_result-store';

export type ShareActor={userId:string;tenantId:string};
export class ShareStoreError extends Error{constructor(public status:number,public code:string,message:string,public details?:unknown){super(message);this.name='ShareStoreError';}}
type ResultRow={id:string;tenant_id:string;project_id:string|null;created_by_user_id:string;current_revision:number;deleted_at:string|null;title:string};
type ShareRow={id:string;tenant_id:string;result_id:string;revision_number:number;share_kind:'public'|'private';created_by_user_id:string;recipient_user_id:string|null;token_prefix:string|null;token_hash:string|null;password_hash:string|null;download_allowed:number;expires_at:string;revoked_at:string|null;created_at:string};
type SectionRow={section_key:(typeof RESULT_SECTION_KEYS)[number];title:string;content:string;source_ids_json:string};

function record(v:unknown):Record<string,unknown>{return v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{};}
function text(v:unknown):string{return typeof v==='string'?v.trim():'';}
function bytesToB64url(bytes:Uint8Array):string{let binary='';for(const b of bytes)binary+=String.fromCharCode(b);return btoa(binary).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
function b64urlToBytes(value:string):Uint8Array{const base=value.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-value.length%4)%4);const binary=atob(base);return Uint8Array.from(binary,c=>c.charCodeAt(0));}
async function sha256(value:string):Promise<string>{const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return [...new Uint8Array(digest)].map(v=>v.toString(16).padStart(2,'0')).join('');}
async function passwordHash(password:string):Promise<string>{const salt=crypto.getRandomValues(new Uint8Array(16)),iterations=120000,key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']),bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt,iterations},key,256);return `pbkdf2-sha256:${iterations}:${bytesToB64url(salt)}:${bytesToB64url(new Uint8Array(bits))}`;}
async function passwordMatches(password:string,encoded:string):Promise<boolean>{const [kind,rawIter,saltRaw,expectedRaw]=encoded.split(':');if(kind!=='pbkdf2-sha256'||!rawIter||!saltRaw||!expectedRaw)return false;const iterations=Number(rawIter);if(!Number.isInteger(iterations)||iterations<100000)return false;const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']),bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:b64urlToBytes(saltRaw),iterations},key,256),actual=new Uint8Array(bits),expected=b64urlToBytes(expectedRaw);if(actual.length!==expected.length)return false;let diff=0;for(let i=0;i<actual.length;i++)diff|=actual[i]^expected[i];return diff===0;}
function status(row:ShareRow):'active'|'expired'|'revoked'{if(row.revoked_at)return'revoked';if(Date.parse(row.expires_at)<=Date.now())return'expired';return'active';}

async function assertShareCreateAccess(db:D1Database,actor:ShareActor,resultId:string):Promise<ResultRow>{
 const row=await db.prepare(`SELECT id,tenant_id,project_id,created_by_user_id,current_revision,deleted_at,title FROM results WHERE id=?1 AND tenant_id=?2 LIMIT 1`).bind(resultId,actor.tenantId).first<ResultRow>();
 if(!row||row.deleted_at)throw new ShareStoreError(404,'RESULT_NOT_FOUND','共有対象Resultが見つかりません。');
 if(row.project_id){const member=await db.prepare(`SELECT role FROM project_members WHERE project_id=?1 AND tenant_id=?2 AND user_id=?3 LIMIT 1`).bind(row.project_id,actor.tenantId,actor.userId).first<{role:string}>();if(!member||!['owner','editor'].includes(member.role))throw new ShareStoreError(403,'SHARE_CREATE_PERMISSION_REQUIRED','Share作成権限がありません。');}
 else if(row.created_by_user_id!==actor.userId)throw new ShareStoreError(403,'SHARE_CREATE_PERMISSION_REQUIRED','Share作成権限がありません。');
 return row;
}
async function snapshot(db:D1Database,resultId:string,revision:number):Promise<NormalizedResultSection[]>{
 const rev=await db.prepare(`SELECT id FROM result_revisions WHERE result_id=?1 AND revision_number=?2 LIMIT 1`).bind(resultId,revision).first<{id:string}>();if(!rev)throw new ShareStoreError(404,'RESULT_REVISION_NOT_FOUND','共有対象Revisionが見つかりません。');
 const rows=(await db.prepare(`SELECT section_key,title,content,source_ids_json FROM result_sections WHERE revision_id=?1`).bind(rev.id).all<SectionRow>()).results??[];const map=new Map(rows.map(r=>[r.section_key,r]));
 const sections:NormalizedResultSection[]=[];for(const key of RESULT_SECTION_KEYS){const r=map.get(key);if(r)sections.push({key,title:r.title,body:r.content,sourceIds:JSON.parse(r.source_ids_json||'[]')});}if(sections.length!==8)throw new ShareStoreError(409,'SHARE_SNAPSHOT_INVALID','共有Snapshotの固定8Sectionが不足しています。');return sections;
}
async function getShareById(db:D1Database,id:string):Promise<ShareRow>{const row=await db.prepare(`SELECT id,tenant_id,result_id,revision_number,share_kind,created_by_user_id,recipient_user_id,token_prefix,token_hash,password_hash,download_allowed,expires_at,revoked_at,created_at FROM result_shares WHERE id=?1 LIMIT 1`).bind(id).first<ShareRow>();if(!row)throw new ShareStoreError(404,'SHARE_NOT_FOUND','Shareが見つかりません。');return row;}
function sharePublic(row:ShareRow){return{id:row.id,share_id:row.id,result_id:row.result_id,revision_number:Number(row.revision_number),visibility:row.share_kind,recipient_user_id:row.recipient_user_id,token_prefix:row.token_prefix,download_allowed:Boolean(row.download_allowed),expires_at:row.expires_at,created_at:row.created_at,status:status(row)};}

export async function listShares(db:D1Database,actor:ShareActor){const rows=(await db.prepare(`SELECT id,tenant_id,result_id,revision_number,share_kind,created_by_user_id,recipient_user_id,token_prefix,token_hash,password_hash,download_allowed,expires_at,revoked_at,created_at FROM result_shares WHERE tenant_id=?1 AND created_by_user_id=?2 ORDER BY created_at DESC`).bind(actor.tenantId,actor.userId).all<ShareRow>()).results??[];return{shares:rows.map(sharePublic)};}
export async function createShare(db:D1Database,actor:ShareActor,value:unknown){const body=record(value),resultId=text(body.result_id??body.resultId),visibility=text(body.visibility??body.share_kind);if(!resultId)throw new ShareStoreError(422,'SHARE_RESULT_REQUIRED','result_idが必要です。');if(!['public','private'].includes(visibility))throw new ShareStoreError(422,'SHARE_VISIBILITY_INVALID','visibilityはpublic/privateです。');const result=await assertShareCreateAccess(db,actor,resultId),revision=Number(body.revision??body.revision_number??result.current_revision);if(!Number.isInteger(revision)||revision<1)throw new ShareStoreError(422,'SHARE_REVISION_INVALID','Revisionが不正です。');await snapshot(db,result.id,revision);
 const now=new Date(),rawExpiry=text(body.expires_at),expiresAt=rawExpiry?new Date(rawExpiry):visibility==='public'?new Date(now.getTime()+7*24*60*60*1000):null;if(!expiresAt||!Number.isFinite(expiresAt.getTime())||expiresAt.getTime()<=now.getTime()||expiresAt.getTime()>now.getTime()+90*24*60*60*1000)throw new ShareStoreError(422,'SHARE_EXPIRY_INVALID','共有期限は現在から90日以内の未来日時です。');const id=crypto.randomUUID(),download=body.download_allowed===true?1:0;
 if(visibility==='public'){const token=bytesToB64url(crypto.getRandomValues(new Uint8Array(32))),tokenHash=await sha256(token),prefix=token.slice(0,8),password=text(body.password);if(password&&password.length<8)throw new ShareStoreError(422,'SHARE_PASSWORD_TOO_SHORT','Passwordは8文字以上です。');const pwh=password?await passwordHash(password):null;await db.prepare(`INSERT INTO result_shares(id,tenant_id,result_id,revision_number,share_kind,created_by_user_id,recipient_user_id,token_prefix,token_hash,password_hash,download_allowed,expires_at,revoked_at,created_at) VALUES(?1,?2,?3,?4,'public',?5,NULL,?6,?7,?8,?9,?10,NULL,?11)`).bind(id,actor.tenantId,result.id,revision,actor.userId,prefix,tokenHash,pwh,download,expiresAt.toISOString(),now.toISOString()).run();return{share:{...sharePublic(await getShareById(db,id)),url:`/s/${token}`,secret_display:'one_time'}};}
 const recipient=text(body.recipient_user_id??body.recipientUserId);if(!recipient||recipient===actor.userId)throw new ShareStoreError(422,'SHARE_RECIPIENT_INVALID','共有先Accountを確認してください。');const recipientExists=await db.prepare(`SELECT id FROM user WHERE id=?1 LIMIT 1`).bind(recipient).first<{id:string}>();if(!recipientExists)throw new ShareStoreError(422,'SHARE_RECIPIENT_INVALID','共有先Accountを確認してください。');await db.prepare(`INSERT INTO result_shares(id,tenant_id,result_id,revision_number,share_kind,created_by_user_id,recipient_user_id,token_prefix,token_hash,password_hash,download_allowed,expires_at,revoked_at,created_at) VALUES(?1,?2,?3,?4,'private',?5,?6,NULL,NULL,NULL,?7,?8,NULL,?9)`).bind(id,actor.tenantId,result.id,revision,actor.userId,recipient,download,expiresAt.toISOString(),now.toISOString()).run();return{share:sharePublic(await getShareById(db,id)),url:`/share/${id}`};}
export async function revokeShare(db:D1Database,actor:ShareActor,id:string){const row=await getShareById(db,id);if(row.tenant_id!==actor.tenantId||row.created_by_user_id!==actor.userId)throw new ShareStoreError(404,'SHARE_NOT_FOUND','Shareが見つかりません。');if(!row.revoked_at)await db.prepare(`UPDATE result_shares SET revoked_at=?1 WHERE id=?2 AND tenant_id=?3 AND created_by_user_id=?4`).bind(new Date().toISOString(),id,actor.tenantId,actor.userId).run();return{share_id:id,status:'revoked'};}
export async function getPrivateShare(db:D1Database,actor:ShareActor,id:string){const row=await getShareById(db,id);if(row.share_kind!=='private'||row.recipient_user_id!==actor.userId)throw new ShareStoreError(404,'SHARE_NOT_FOUND','Shareが見つかりません。');const s=status(row);if(s!=='active')throw new ShareStoreError(s==='expired'?410:404,s==='expired'?'SHARE_EXPIRED':'SHARE_REVOKED',s==='expired'?'Shareの期限が切れています。':'Shareは失効しています。');return{share:sharePublic(row),sections:await snapshot(db,row.result_id,row.revision_number)};}
export async function getPublicShare(db:D1Database,token:string,password?:string){if(token.length<32)throw new ShareStoreError(404,'SHARE_NOT_FOUND','Shareが見つかりません。');const hash=await sha256(token),row=await db.prepare(`SELECT id,tenant_id,result_id,revision_number,share_kind,created_by_user_id,recipient_user_id,token_prefix,token_hash,password_hash,download_allowed,expires_at,revoked_at,created_at FROM result_shares WHERE share_kind='public' AND token_hash=?1 LIMIT 1`).bind(hash).first<ShareRow>();if(!row)throw new ShareStoreError(404,'SHARE_NOT_FOUND','Shareが見つかりません。');const s=status(row);if(s!=='active')throw new ShareStoreError(s==='expired'?410:404,s==='expired'?'SHARE_EXPIRED':'SHARE_REVOKED',s==='expired'?'Shareの期限が切れています。':'Shareは失効しています。');if(row.password_hash){if(!password)throw new ShareStoreError(401,'SHARE_PASSWORD_REQUIRED','Passwordが必要です。');if(!await passwordMatches(password,row.password_hash))throw new ShareStoreError(403,'SHARE_PASSWORD_INVALID','Passwordを確認できません。');}return{share:sharePublic(row),sections:await snapshot(db,row.result_id,row.revision_number)};}
