import type { D1Database } from './_account-projection';
export type StorageActor={userId:string;tenantId:string};export type StorageContract={capacityBytes:number;writeAllowed:boolean;state:string};
export type StorageObjectRow={id:string;tenant_id:string;user_id:string;project_id:string|null;folder_id:string|null;topic_id:string|null;message_id:string|null;file_name:string;mime_type:string;file_size:number;checksum_sha256:string|null;checksum_verified_at:string|null;encryption_profile:string|null;dek_wrap_ciphertext:string|null;dek_wrap_iv:string|null;content_iv_base64:string|null;auth_tag_base64:string|null;encrypted_at:string|null;retention_policy:string|null;source_result_id:string|null;version:number;contract_capacity_bytes_snapshot:number;status:string;error_code:string|null;deleted_at:string|null;restored_at:string|null;primary_deleted_at:string|null;created_at:string;updated_at:string};
export class StorageStoreError extends Error{constructor(public status:number,public code:string,message:string,public details?:unknown){super(message);this.name='StorageStoreError';}}
function payload(r:StorageObjectRow){return{id:r.id,object_id:r.id,project_id:r.project_id,folder_id:r.folder_id,file_name:r.file_name,mime_type:r.mime_type,file_size:Number(r.file_size),checksum_sha256:r.checksum_sha256,checksum_verified_at:r.checksum_verified_at,encryption_profile:r.encryption_profile,retention_policy:r.retention_policy,source_result_id:r.source_result_id,version:Number(r.version),status:r.status,error_code:r.error_code,deleted_at:r.deleted_at,restored_at:r.restored_at,primary_deleted_at:r.primary_deleted_at,created_at:r.created_at,updated_at:r.updated_at};}
async function owned(db:D1Database,a:StorageActor,id:string):Promise<StorageObjectRow>{const r=await db.prepare(`SELECT * FROM astera_storage_objects WHERE id=?1 AND tenant_id=?2 AND user_id=?3 LIMIT 1`).bind(id,a.tenantId,a.userId).first<StorageObjectRow>();if(!r)throw new StorageStoreError(404,'ASTERA_STORAGE_OBJECT_NOT_FOUND','Storage objectが見つかりません。');return r;}
export async function usage(db:D1Database,a:StorageActor,c:StorageContract){const r=await db.prepare(`SELECT COALESCE(SUM(CASE WHEN status='stored' THEN file_size ELSE 0 END),0) used,COALESCE(SUM(CASE WHEN status='pending' THEN file_size ELSE 0 END),0) reserved,COALESCE(SUM(CASE WHEN status IN ('soft_deleted','deleting') THEN file_size ELSE 0 END),0) pending_deletion FROM astera_storage_objects WHERE tenant_id=?1`).bind(a.tenantId).first<{used:number;reserved:number;pending_deletion:number}>();const used=Number(r?.used??0),reserved=Number(r?.reserved??0),pending=Number(r?.pending_deletion??0),occupied=used+reserved+pending;if(![used,reserved,pending,occupied].every(Number.isSafeInteger))throw new StorageStoreError(500,'ASTERA_STORAGE_USAGE_OVERFLOW','Storage usageを安全に表現できません。');return{capacity_bytes:c.capacityBytes,used_bytes:used,reserved_bytes:reserved,pending_deletion_bytes:pending,remaining_bytes:Math.max(0,c.capacityBytes-occupied),state:c.state,write_allowed:c.writeAllowed};}
export async function listObjects(db:D1Database,a:StorageActor,includeDeleted=false,projectId:string|null=null){const rows=(await db.prepare(`SELECT * FROM astera_storage_objects WHERE tenant_id=?1 AND user_id=?2 AND (?3 IS NULL OR project_id=?3) AND (?4=1 OR status NOT IN ('soft_deleted','deleted')) ORDER BY created_at DESC LIMIT 200`).bind(a.tenantId,a.userId,projectId,includeDeleted?1:0).all<StorageObjectRow>()).results??[];return{objects:rows.map(payload)};}
export async function getObject(db:D1Database,a:StorageActor,id:string){return{object:payload(await owned(db,a,id))};}
export async function assertStorageRefs(db:D1Database,a:StorageActor,projectId:string|null,sourceResultId:string|null){if(projectId){const m=await db.prepare(`SELECT role FROM project_members WHERE project_id=?1 AND tenant_id=?2 AND user_id=?3 LIMIT 1`).bind(projectId,a.tenantId,a.userId).first<{role:string}>();if(!m||!['owner','editor'].includes(m.role))throw new StorageStoreError(403,'PROJECT_WRITE_PERMISSION_REQUIRED','ProjectへのStorage書込権限がありません。');}if(sourceResultId){const r=await db.prepare(`SELECT id,project_id,created_by_user_id FROM results WHERE id=?1 AND tenant_id=?2 AND deleted_at IS NULL LIMIT 1`).bind(sourceResultId,a.tenantId).first<{id:string;project_id:string|null;created_by_user_id:string}>();if(!r)throw new StorageStoreError(404,'SOURCE_RESULT_NOT_FOUND','Source Resultが見つかりません。');if(r.project_id){const m=await db.prepare(`SELECT user_id FROM project_members WHERE project_id=?1 AND tenant_id=?2 AND user_id=?3 LIMIT 1`).bind(r.project_id,a.tenantId,a.userId).first<{user_id:string}>();if(!m)throw new StorageStoreError(403,'SOURCE_RESULT_ACCESS_DENIED','Source ResultへのAccess権がありません。');}else if(r.created_by_user_id!==a.userId)throw new StorageStoreError(403,'SOURCE_RESULT_ACCESS_DENIED','Source ResultへのAccess権がありません。');}}
export async function reserveObject(db:D1Database,a:StorageActor,input:{id:string;projectId:string|null;folderId:string|null;fileName:string;mimeType:string;fileSize:number;sourceResultId:string|null;capacityBytes:number}){const now=new Date().toISOString();const result=await db.prepare(`INSERT INTO astera_storage_objects(id,tenant_id,user_id,project_id,folder_id,file_name,mime_type,file_size,source_result_id,version,contract_capacity_bytes_snapshot,status,created_at,updated_at) SELECT ?1,?2,?3,?4,?5,?6,?7,?8,?9,1,?10,'pending',?11,?11 WHERE ?10 >= ?8 + COALESCE((SELECT SUM(file_size) FROM astera_storage_objects WHERE tenant_id=?2 AND status IN ('pending','stored','soft_deleted','deleting')),0)`).bind(input.id,a.tenantId,a.userId,input.projectId,input.folderId,input.fileName,input.mimeType,input.fileSize,input.sourceResultId,input.capacityBytes,now).run();const changes=Number(result.meta?.changes??0);if(changes!==1)throw new StorageStoreError(409,'ASTERA_STORAGE_QUOTA_EXCEEDED','Storage quotaを超えています。');return owned(db,a,input.id);}
export async function commitObject(db:D1Database,a:StorageActor,id:string,m:{topicId:string;messageId:string;checksumSha256:string;encryptionProfile:string;dekWrapCiphertext:string;dekWrapIv:string;contentIvBase64:string;authTagBase64:string;encryptedAt:string}){const now=new Date().toISOString();await db.prepare(`UPDATE astera_storage_objects SET topic_id=?1,message_id=?2,checksum_sha256=?3,checksum_verified_at=?4,encryption_profile=?5,dek_wrap_ciphertext=?6,dek_wrap_iv=?7,content_iv_base64=?8,auth_tag_base64=?9,encrypted_at=?10,status='stored',error_code=NULL,updated_at=?4 WHERE id=?11 AND tenant_id=?12 AND user_id=?13 AND status='pending'`).bind(m.topicId,m.messageId,m.checksumSha256,now,m.encryptionProfile,m.dekWrapCiphertext,m.dekWrapIv,m.contentIvBase64,m.authTagBase64,m.encryptedAt,id,a.tenantId,a.userId).run();const r=await owned(db,a,id);if(r.status!=='stored')throw new StorageStoreError(500,'ASTERA_STORAGE_COMMIT_FAILED','Storage metadataを確定できませんでした。');return payload(r);}
export async function markObjectError(db:D1Database,id:string,code:string){await db.prepare(`UPDATE astera_storage_objects SET status='error',error_code=?1,updated_at=?2 WHERE id=?3 AND status='pending'`).bind(code,new Date().toISOString(),id).run();}
export async function markVerified(db:D1Database,a:StorageActor,id:string){await db.prepare(`UPDATE astera_storage_objects SET checksum_verified_at=?1,error_code=NULL,updated_at=?1 WHERE id=?2 AND tenant_id=?3 AND user_id=?4 AND status='stored'`).bind(new Date().toISOString(),id,a.tenantId,a.userId).run();}
export async function markCorrupt(db:D1Database,a:StorageActor,id:string,code:string){await db.prepare(`UPDATE astera_storage_objects SET status='corrupt',error_code=?1,updated_at=?2 WHERE id=?3 AND tenant_id=?4 AND user_id=?5`).bind(code,new Date().toISOString(),id,a.tenantId,a.userId).run();}
export async function softDelete(db:D1Database,a:StorageActor,id:string){const cur=await owned(db,a,id);if(cur.status==='soft_deleted')return{object:payload(cur),undo_available:true};if(!['stored','corrupt'].includes(cur.status))throw new StorageStoreError(409,'ASTERA_STORAGE_OBJECT_NOT_DELETABLE','Storage objectは現在削除できません。');const now=new Date().toISOString();await db.prepare(`UPDATE astera_storage_objects SET status='soft_deleted',deleted_at=?1,updated_at=?1 WHERE id=?2 AND tenant_id=?3 AND user_id=?4 AND status IN ('stored','corrupt')`).bind(now,id,a.tenantId,a.userId).run();return{object:payload(await owned(db,a,id)),undo_available:true};}
export async function undoDelete(db:D1Database,a:StorageActor,id:string){const cur=await owned(db,a,id);if(cur.status!=='soft_deleted')throw new StorageStoreError(404,'ASTERA_STORAGE_OBJECT_NOT_RESTORABLE','Storage objectは復元可能状態ではありません。');const now=new Date().toISOString(),next=cur.error_code?'corrupt':'stored';await db.prepare(`UPDATE astera_storage_objects SET status=?1,deleted_at=NULL,restored_at=?2,updated_at=?2 WHERE id=?3 AND tenant_id=?4 AND user_id=?5 AND status='soft_deleted'`).bind(next,now,id,a.tenantId,a.userId).run();return{object:payload(await owned(db,a,id))};}
export async function binaryDescriptor(db:D1Database,a:StorageActor,id:string){const r=await owned(db,a,id);if(r.status!=='stored'||!r.topic_id||!r.message_id||!r.checksum_sha256||!r.encryption_profile||!r.dek_wrap_ciphertext||!r.dek_wrap_iv||!r.content_iv_base64||!r.auth_tag_base64)throw new StorageStoreError(409,'ASTERA_STORAGE_OBJECT_NOT_DOWNLOADABLE','Storage objectはDownloadできません。');return r;}
