import { FunctionHttpError, functionErrorResponse, requestCorrelationId, requireAsteraActor, type AsteraFunctionEnv } from '../../../_account-projection';
import { ExternalStorageStoreError, getExternalStorageDestination, revokeExternalStorageDestination, updateExternalStorageDestination } from '../../../_external-storage-store';
type C={request:Request;env:AsteraFunctionEnv;params:{destination?:string}};
const norm=(error:unknown)=>error instanceof ExternalStorageStoreError?new FunctionHttpError(error.status,error.code,error.message,error.details):error;
function destinationId(c:C){const id=c.params.destination?.trim();if(!id)throw new FunctionHttpError(400,'STORAGE_DESTINATION_ID_REQUIRED','Destination IDが必要です。');return id;}
async function actor(c:C){const a=await requireAsteraActor(c.request,c.env);return{userId:a.user.id,tenantId:a.profile.tenant_id};}
export async function onRequestGet(c:C){const cid=requestCorrelationId(c.request);try{return Response.json(await getExternalStorageDestination(c.env.ASTERA_DB,await actor(c),destinationId(c)),{headers:{'Cache-Control':'no-store','X-Correlation-ID':cid}});}catch(error){return functionErrorResponse(norm(error),cid);}}
export async function onRequestPatch(c:C){const cid=requestCorrelationId(c.request);try{return Response.json(await updateExternalStorageDestination(c.env.ASTERA_DB,await actor(c),destinationId(c),await c.request.json().catch(()=>null)),{headers:{'Cache-Control':'no-store','X-Correlation-ID':cid}});}catch(error){return functionErrorResponse(norm(error),cid);}}
export async function onRequestDelete(c:C){const cid=requestCorrelationId(c.request);try{return Response.json(await revokeExternalStorageDestination(c.env.ASTERA_DB,await actor(c),destinationId(c)),{headers:{'Cache-Control':'no-store','X-Correlation-ID':cid}});}catch(error){return functionErrorResponse(norm(error),cid);}}
export function onRequest(c:C){if(c.request.method==='GET')return onRequestGet(c);if(c.request.method==='PATCH')return onRequestPatch(c);if(c.request.method==='DELETE')return onRequestDelete(c);return Promise.resolve(Response.json({error:{code:'METHOD_NOT_ALLOWED',message:'GET/PATCH/DELETEのみ対応しています。'}},{status:405}));}
