import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import { binaryDescriptor, commitObject, StorageStoreError } from '../functions/_storage-store.ts';

const actor={userId:'user-1',tenantId:'tenant-1'};
function row(overrides={}){return{id:'obj-1',tenant_id:'tenant-1',user_id:'user-1',project_id:null,folder_id:null,topic_id:'10',message_id:'20',telegram_file_id:'legacy-file',tgs_profile:'legacy_v15',tgs_namespace_ref:null,tgs_object_ref:null,tgs_operation_id:null,tgs_commit_state:null,tgs_last_reconciled_at:null,file_name:'a.txt',mime_type:'text/plain',file_size:3,checksum_sha256:'a'.repeat(64),checksum_verified_at:null,encryption_profile:'AES-256-GCM',dek_wrap_ciphertext:'dek',dek_wrap_iv:'iv',content_iv_base64:'civ',auth_tag_base64:'tag',encrypted_at:'2026-10-03T00:00:00.000Z',retention_policy:null,source_result_id:null,version:1,contract_capacity_bytes_snapshot:100,status:'stored',error_code:null,deleted_at:null,restored_at:null,primary_deleted_at:null,created_at:'2026-10-03T00:00:00.000Z',updated_at:'2026-10-03T00:00:00.000Z',...overrides};}
function fakeDb(resultRow){const runs=[];return{runs,db:{prepare(sql){const statement={values:[],bind(...values){statement.values=values;return statement;},async first(){return resultRow;},async all(){return{results:[]};},async run(){runs.push({sql,values:statement.values});return{meta:{changes:1}};}};return statement;},async batch(){return[];}}};}
const common={checksumSha256:'a'.repeat(64),encryptionProfile:'AES-256-GCM',dekWrapCiphertext:'dek',dekWrapIv:'iv',contentIvBase64:'civ',authTagBase64:'tag',encryptedAt:'2026-10-03T00:00:00.000Z'};

test('0025 adds logical TGserver reference authority without deleting legacy refs',()=>{const sql=readFileSync(new URL('../migrations/d1/0025_tgserver_logical_object_refs.sql',import.meta.url),'utf8');for(const name of ['tgs_profile','tgs_namespace_ref','tgs_object_ref','tgs_operation_id','tgs_commit_state','tgs_last_reconciled_at'])assert.match(sql,new RegExp(`ADD COLUMN ${name}`));assert.match(sql,/DEFAULT 'legacy_v15'/);assert.match(sql,/WHERE tgs_profile = 'native_v1'/);});

test('native commit clears legacy locators and persists committed logical identity',async()=>{const f=fakeDb(row({topic_id:null,message_id:null,telegram_file_id:null,tgs_profile:'native_v1',tgs_object_ref:'native-object-1',tgs_operation_id:null,tgs_commit_state:'committed'}));await commitObject(f.db,actor,'obj-1',{reference:{profile:'native_v1',objectRef:'native-object-1',operationId:null,commitState:'committed'},...common});assert.equal(f.runs.length,1);assert.match(f.runs[0].sql,/tgs_profile=\?1,topic_id=\?2,message_id=\?3,telegram_file_id=\?4,tgs_object_ref=\?5/);assert.deepEqual(f.runs[0].values.slice(0,7),['native_v1',null,null,null,'native-object-1',null,'committed']);});

test('legacy commit preserves physical locator and clears native logical fields',async()=>{const f=fakeDb(row());await commitObject(f.db,actor,'obj-1',{reference:{profile:'legacy_v15',topicId:'10',messageId:'20',telegramFileId:'legacy-file'},...common});assert.deepEqual(f.runs[0].values.slice(0,7),['legacy_v15','10','20','legacy-file',null,null,null]);});

test('binary descriptor accepts committed native object with no Telegram locator',async()=>{const f=fakeDb(row({topic_id:null,message_id:null,telegram_file_id:null,tgs_profile:'native_v1',tgs_object_ref:'native-object-1',tgs_commit_state:'committed'}));const descriptor=await binaryDescriptor(f.db,actor,'obj-1');assert.equal(descriptor.tgs_profile,'native_v1');assert.equal(descriptor.tgs_object_ref,'native-object-1');});

test('binary descriptor rejects native object without committed evidence',async()=>{const f=fakeDb(row({topic_id:null,message_id:null,telegram_file_id:null,tgs_profile:'native_v1',tgs_object_ref:'native-object-1',tgs_commit_state:'accepted'}));await assert.rejects(()=>binaryDescriptor(f.db,actor,'obj-1'),error=>error instanceof StorageStoreError&&error.code==='ASTERA_STORAGE_OBJECT_NOT_DOWNLOADABLE');});

test('Cloudflare storage bridge persists and reads native logical refs without raw Telegram requirements',()=>{const complete=readFileSync(new URL('../functions/api/storage/uploads/[object]/complete.ts',import.meta.url),'utf8');const download=readFileSync(new URL('../functions/api/storage/objects/[object]/download.ts',import.meta.url),'utf8');assert.match(complete,/profile === 'native_v1'/);assert.match(complete,/tgs_object_ref/);assert.match(complete,/commitState: 'committed'/);assert.match(download,/X-Astera-TGS-Profile/);assert.match(download,/X-Astera-TGS-Object-Ref/);assert.match(download,/if\(r\.tgs_profile==='native_v1'\)/);});
