export type RuntimeState='queued'|'running'|'assembling_result'|'completed'|'partially_completed'|'failed'|'cancel_requested'|'cancelled';
export type RuntimeJobRow={id:string;tenant_id:string;user_id:string;request_id:string;state:RuntimeState;purpose:string;private_mode:boolean;project_id:string|null;policy_version:string;reserved_credits:string;request_ciphertext:string|null;request_iv:string|null;result_json:unknown|null;usage_json:unknown|null;error_code:string|null;error_message:string|null;retryable:boolean;correlation_id:string;created_at:Date;updated_at:Date;started_at:Date|null;completed_at:Date|null;cancelled_at:Date|null};
export type InsertRuntimeJob={id:string;tenantId:string;userId:string;requestId:string;purpose:string;privateMode:boolean;projectId:string|null;policyVersion:string;reservedCredits:number;requestCiphertext:string|null;requestIv:string|null;correlationId:string};
export type TerminalUpdate={state:'completed'|'partially_completed'|'failed'|'cancelled';result?:unknown;usage?:unknown;errorCode?:string|null;errorMessage?:string|null;retryable?:boolean};
const TERMINAL=new Set<RuntimeState>(['completed','partially_completed','failed','cancelled']);
const RETAIN_MS=2*60*60*1000;
const copy=(j:RuntimeJobRow):RuntimeJobRow=>({...j,created_at:new Date(j.created_at),updated_at:new Date(j.updated_at),started_at:j.started_at?new Date(j.started_at):null,completed_at:j.completed_at?new Date(j.completed_at):null,cancelled_at:j.cancelled_at?new Date(j.cancelled_at):null});
function lost(id:string):RuntimeJobRow{const now=new Date();return{id,tenant_id:'',user_id:'',request_id:'',state:'failed',purpose:'auto',private_mode:false,project_id:null,policy_version:'',reserved_credits:'0',request_ciphertext:null,request_iv:null,result_json:null,usage_json:null,error_code:'RUNTIME_STATE_LOST_AFTER_RESTART',error_message:'Runtime Memory Stateが失われました。Cloudflare D1側でJobを失敗確定し、予約CreditをReleaseしてください。',retryable:false,correlation_id:'',created_at:now,updated_at:now,started_at:null,completed_at:now,cancelled_at:null};}
/** Cloudflare D1 app_jobs is the only persistent App Job authority. */
export class RuntimeDatabase{
 private readonly jobs=new Map<string,RuntimeJobRow>(); private readonly requests=new Map<string,string>();
 // Temporary compatibility parameter until legacy migrate/smoke sources are removed.
 constructor(_legacyDatabaseUrl=''){}
 async ready():Promise<void>{}
 async close():Promise<void>{this.jobs.clear();this.requests.clear();}
 private key(t:string,r:string){return `${t}\u0000${r}`;}
 private prune(now=Date.now()){for(const[id,j]of this.jobs){if(TERMINAL.has(j.state)&&now-j.updated_at.getTime()>RETAIN_MS){this.jobs.delete(id);this.requests.delete(this.key(j.tenant_id,j.request_id));}}}
 async insertOrGet(i:InsertRuntimeJob):Promise<{job:RuntimeJobRow;created:boolean}>{this.prune();const k=this.key(i.tenantId,i.requestId),eid=this.requests.get(k);if(eid){const e=this.jobs.get(eid);if(e){if(e.user_id!==i.userId)throw new Error('RUNTIME_JOB_IDEMPOTENCY_OWNERSHIP_MISMATCH');return{job:copy(e),created:false};}this.requests.delete(k);}const same=this.jobs.get(i.id);if(same){if(same.tenant_id!==i.tenantId||same.user_id!==i.userId||same.request_id!==i.requestId)throw new Error('RUNTIME_JOB_ID_COLLISION');return{job:copy(same),created:false};}const now=new Date(),j:RuntimeJobRow={id:i.id,tenant_id:i.tenantId,user_id:i.userId,request_id:i.requestId,state:'queued',purpose:i.purpose,private_mode:i.privateMode,project_id:i.projectId,policy_version:i.policyVersion,reserved_credits:String(i.reservedCredits),request_ciphertext:i.requestCiphertext,request_iv:i.requestIv,result_json:null,usage_json:null,error_code:null,error_message:null,retryable:false,correlation_id:i.correlationId,created_at:now,updated_at:now,started_at:null,completed_at:null,cancelled_at:null};this.jobs.set(j.id,j);this.requests.set(k,j.id);return{job:copy(j),created:true};}
 async get(id:string):Promise<RuntimeJobRow|null>{this.prune();const j=this.jobs.get(id);return j?copy(j):lost(id);}
 async transition(id:string,expected:RuntimeState[],next:RuntimeState,cid:string,_metadata:Record<string,unknown>={}):Promise<RuntimeJobRow|null>{const j=this.jobs.get(id);if(!j)return null;if(!expected.includes(j.state))return copy(j);const now=new Date();j.state=next;j.correlation_id=cid||j.correlation_id;j.updated_at=now;if(next==='running'&&!j.started_at)j.started_at=now;if(next==='cancelled')j.cancelled_at=now;return copy(j);}
 async finish(id:string,u:TerminalUpdate,cid:string):Promise<RuntimeJobRow>{const j=this.jobs.get(id);if(!j)throw new Error('RUNTIME_JOB_NOT_FOUND');if(TERMINAL.has(j.state))return copy(j);const now=new Date();j.state=u.state;j.result_json=j.private_mode||u.result===undefined?null:structuredClone(u.result);j.usage_json=u.usage===undefined?null:structuredClone(u.usage);j.error_code=u.errorCode??null;j.error_message=u.errorMessage??null;j.retryable=u.retryable??false;j.request_ciphertext=null;j.request_iv=null;j.correlation_id=cid||j.correlation_id;j.updated_at=now;if(['completed','partially_completed','failed'].includes(u.state))j.completed_at=now;if(u.state==='cancelled')j.cancelled_at=now;return copy(j);}
 async recoverable():Promise<RuntimeJobRow[]>{return[];}
}
