import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import type { AddressInfo } from 'node:net';
import { once } from 'node:events';
import { createFullApp } from './full-app.js';
import type { RuntimeConfig } from './config.js';

function closeServer(server:ReturnType<typeof createServer>):Promise<void>{if(!server.listening)return Promise.resolve();return new Promise((resolve,reject)=>server.close(error=>error?reject(error):resolve()));}
let processCalls=0;
const main8=[['01 本当の目的','- 目的'],['02 前提不足','- 前提'],['03 事実確認','- 事実'],['04 危機察知','- リスク'],['05 反対視点','- 反対'],['06 比較案','- 比較'],['07 根拠成立状態','- 根拠'],['08 主役AI／利用者への再指示','- 再指示']].map(([title,body])=>`${title}\n${body}`).join('\n---\n');
const processServer=createServer(async(req,res)=>{if(req.method!=='POST'||req.url!=='/process'){res.writeHead(404).end();return;}assert.equal(req.headers['x-api-key'],'process-test-token');assert.equal(req.headers.authorization,undefined);const chunks:Buffer[]=[];for await(const chunk of req)chunks.push(Buffer.isBuffer(chunk)?chunk:Buffer.from(chunk));const body=JSON.parse(Buffer.concat(chunks).toString('utf8')) as Record<string,unknown>;assert.equal(typeof body.question,'string');assert.equal(Object.hasOwn(body,'actor'),false);assert.equal(Object.hasOwn(body,'job'),false);processCalls+=1;if(processCalls===1){assert.equal(body.question,'Smoke Test');const context=JSON.parse(String(body.context||'')) as {app_purpose_contract?:{version?:string;selected_by?:string;purpose?:string;required_focus?:string[]}};assert.equal(context.app_purpose_contract?.version,'app-purpose-v1');assert.equal(context.app_purpose_contract?.selected_by,'user');assert.equal(context.app_purpose_contract?.purpose,'verify');assert.ok(context.app_purpose_contract?.required_focus?.includes('claim_extraction'));}else if(processCalls===2){assert.equal(body.question,'PRIVATE_SMOKE_CANARY_DO_NOT_PERSIST');assert.equal(body.context,undefined);}res.writeHead(200,{'content-type':'text/plain; charset=utf-8'});res.end(main8);});
processServer.listen(0,'127.0.0.1');await once(processServer,'listening');const processPort=(processServer.address() as AddressInfo).port;
let vaultCalls=0;
const vaultServer=createServer(async(req,res)=>{assert.equal(req.headers.authorization,'Bearer vault-test-token');if(req.method==='GET'&&req.url==='/internal/v1/health'){vaultCalls+=1;res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({status:'ok'}));return;}const chunks:Buffer[]=[];for await(const chunk of req)chunks.push(Buffer.isBuffer(chunk)?chunk:Buffer.from(chunk));const body=JSON.parse(Buffer.concat(chunks).toString('utf8')) as Record<string,unknown>;if(req.method==='POST'&&req.url==='/internal/v1/crypto/seal'){vaultCalls+=1;res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({ciphertext:String(body.plaintext_base64||''),iv:'smoke-iv'}));return;}res.writeHead(404,{'content-type':'application/json'});res.end(JSON.stringify({error:{code:'SMOKE_VAULT_ROUTE_NOT_FOUND'}}));});
vaultServer.listen(0,'127.0.0.1');await once(vaultServer,'listening');const vaultPort=(vaultServer.address() as AddressInfo).port;
const config:RuntimeConfig={port:0,internalServiceToken:'internal-test-token',processOrigin:`http://127.0.0.1:${processPort}`,processToken:'process-test-token',processTimeoutMs:5000,shutdownTimeoutMs:5000,vaultOrigin:`http://127.0.0.1:${vaultPort}`,vaultServiceToken:'vault-test-token',vaultJobKeyRef:'smoke-job-key',vaultTimeoutMs:5000,translationModelId:'',translationGeminiKeyRef:'',translationTimeoutMs:5000,tgserverStorageOrigin:'',tgserverStorageToken:'',tgserverStorageTimeoutMs:600000};
const{app,service}=createFullApp(config);
const auth={Authorization:'Bearer internal-test-token','Content-Type':'application/json'};
async function waitJob(id:string){for(let i=0;i<100;i++){const r=await app.request(`/internal/v1/jobs/${id}`,{headers:{Authorization:'Bearer internal-test-token'}});assert.equal(r.status,200);const p=await r.json() as{job:Record<string,unknown>};if(p.job.state==='completed')return p.job;await new Promise(resolve=>setTimeout(resolve,25));}throw new Error('Runtime Job did not complete');}
try{
 assert.equal((await app.request('/internal/v1/jobs/missing')).status,401);
 assert.equal((await app.request('/ready')).status,200);
 const jobId=crypto.randomUUID(),requestId=crypto.randomUUID();const body={job_id:jobId,tenant_id:'tenant-smoke',user_id:'user-smoke',request_id:requestId,prompt:'Smoke Test',purpose:'verify',options:[],files:[],private_mode:false,project_id:null,reserved_credits:10,policy_version:'smoke-policy',correlation_id:crypto.randomUUID()};
 const created=await app.request('/internal/v1/jobs',{method:'POST',headers:auth,body:JSON.stringify(body)});assert.equal(created.status,201);const complete=await waitJob(jobId);assert.ok(complete.result);const completedResult=complete.result as{sections?:Record<string,{title?:string;body?:string;canonical_key?:string}>};assert.equal(completedResult.sections?.recommendation?.title,'07 根拠成立状態');assert.equal(completedResult.sections?.recommendation?.canonical_key,'07_evidence_status');assert.equal(processCalls,1);
 const duplicate=await app.request('/internal/v1/jobs',{method:'POST',headers:auth,body:JSON.stringify(body)});assert.equal(duplicate.status,200);const dup=await duplicate.json() as{created:boolean};assert.equal(dup.created,false);assert.equal(processCalls,1);
 const privateId=crypto.randomUUID(),privateBody={...body,job_id:privateId,request_id:crypto.randomUUID(),prompt:'PRIVATE_SMOKE_CANARY_DO_NOT_PERSIST',purpose:'auto',private_mode:true,correlation_id:crypto.randomUUID()};const pc=await app.request('/internal/v1/jobs',{method:'POST',headers:auth,body:JSON.stringify(privateBody)});assert.equal(pc.status,201);const privateResult=await waitJob(privateId);assert.ok(privateResult.result);const privateRow=await service.database.get(privateId);assert.equal(privateRow?.result_json,null);assert.equal(privateRow?.request_ciphertext,null);assert.equal(privateRow?.request_iv,null);assert.equal(processCalls,2);
 const lost=await service.database.get('restart-loss-canary');assert.equal(lost?.state,'failed');assert.equal(lost?.error_code,'RUNTIME_STATE_LOST_AFTER_RESTART');
 assert.ok(vaultCalls>=2);
 console.log(JSON.stringify({event:'contabo_runtime_smoke_passed',process_calls:processCalls,core_contract:'x-api-key+question-context+main8-text',section_07:'07_evidence_status',private_result_persisted:false,postgres_required:false,restart_loss_fail_closed:true}));
}finally{for(const controller of service.active.values())controller.abort('smoke_shutdown');await service.database.close();await Promise.all([closeServer(processServer),closeServer(vaultServer)]);}
