import type { Pool } from 'pg';
import { assertProjectAccess } from './workspace-api.js';
import { StorageApiError, type StorageActor, type StorageObjectRow } from './storage-api-types.js';
export function safeName(raw:string):string{let d=raw;try{d=decodeURIComponent(raw)}catch{}const v=d.replace(/[\\/:*?"<>|\u0000-\u001f]/g,'_').trim().slice(0,240);if(!v)throw new StorageApiError(422,'STORAGE_FILE_NAME_INVALID','File name is invalid.');return v;}
export function optionalUuid(v:string|undefined,code:string):string|null{const s=v?.trim()||'';if(!s)return null;if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(s))throw new StorageApiError(422,code,code);return s;}
export function checksum(v:string|undefined):string|null{const s=v?.trim().toLowerCase()||'';if(!s)return null;if(!/^[0-9a-f]{64}$/.test(s))throw new StorageApiError(422,'STORAGE_SHA256_INVALID','SHA-256 is invalid.');return s;}
export function objectPayload(r:StorageObjectRow):Record<string,unknown>{return{object_id:r.id,file_id:r.id,project_id:r.project_id,folder_id:r.folder_id,file_name:r.file_name,mime_type:r.mime_type,file_size:Number(r.file_size),hash:r.checksum_sha256,checksum_verified_at:r.checksum_verified_at?.toISOString()??null,encryption_profile:r.encryption_profile,retention_policy:r.retention_policy,source_result_id:r.source_result_id,version:r.version,status:r.status,error_code:r.error_code,created_at:r.created_at.toISOString(),updated_at:r.updated_at.toISOString(),deleted_at:r.deleted_at?.toISOString()??null};}
export async function validateSourceResult(pool:Pool,a:StorageActor,id:string|null):Promise<void>{if(!id)return;const q=await pool.query<{project_id:string|null;created_by_user_id:string|null;private_mode:boolean}>(`SELECT project_id,created_by_user_id,private_mode FROM results WHERE id=$1 AND tenant_id=$2 LIMIT 1`,[id,a.tenantId]);const r=q.rows[0];if(!r||r.private_mode)throw new StorageApiError(404,'STORAGE_SOURCE_RESULT_NOT_FOUND','Source Result is unavailable.');if(r.project_id)await assertProjectAccess(pool,a.tenantId,a.userId,r.project_id,'viewer');else if(r.created_by_user_id&&r.created_by_user_id!==a.userId)throw new StorageApiError(404,'STORAGE_SOURCE_RESULT_NOT_FOUND','Source Result is unavailable.');}
export function requireEncryptionMetadata(r:StorageObjectRow):void{if(r.encryption_profile!=='AES-256-GCM'||!r.dek_wrap_ciphertext||!r.dek_wrap_iv||!r.content_iv_base64||!r.auth_tag_base64||!r.checksum_sha256)throw new StorageApiError(409,'ASTERA_STORAGE_ENCRYPTION_METADATA_REQUIRED','Storage encryption metadata is incomplete.');}
