import { createCipheriv, createDecipheriv, createHash, randomBytes } from 'node:crypto';
import { createWriteStream } from 'node:fs';
import { rm } from 'node:fs/promises';
import { PassThrough, Readable, Transform } from 'node:stream';
import { pipeline } from 'node:stream/promises';
const ALG='AES-256-GCM',KEY_BYTES=32,IV_BYTES=12,TAG_BYTES=16,WRAP_VERSION=1,AAD_VERSION='astera-storage-object-v1';
export type VaultEnvelope=Readonly<{ciphertext:string;iv:string}>;
export type StorageVaultLike={sealJson(v:unknown):Promise<VaultEnvelope>;unsealJson<T>(p:VaultEnvelope):Promise<T>};
export class StorageObjectCryptoError extends Error{constructor(public readonly code:string,message:string){super(message);this.name='StorageObjectCryptoError'}}
const requireId=(v:string)=>{const s=v.trim();if(!s)throw new StorageObjectCryptoError('STORAGE_OBJECT_ID_REQUIRED','Storage Object ID is required.');return s};
const aad=(v:string)=>Buffer.from(JSON.stringify([AAD_VERSION,requireId(v)]),'utf8');
function b64(v:string,n:number,code:string){const b=Buffer.from(v,'base64');if(b.byteLength!==n){b.fill(0);throw new StorageObjectCryptoError(code,code)}return b}
function hexEq(a:string,b:string){if(!/^[0-9a-f]{64}$/.test(a)||!/^[0-9a-f]{64}$/.test(b))return false;const x=Buffer.from(a,'hex'),y=Buffer.from(b,'hex');if(x.length!==y.length)return false;let d=0;for(let i=0;i<x.length;i+=1){const xv=x[i];const yv=y[i];if(xv===undefined||yv===undefined)return false;d|=xv^yv}return d===0}
export async function createStorageEncryptedUpload(objectIdValue:string,plaintext:ReadableStream<Uint8Array>,vault:StorageVaultLike){const objectId=requireId(objectIdValue),key=randomBytes(KEY_BYTES);let wrappedDek:VaultEnvelope;try{wrappedDek=await vault.sealJson({version:WRAP_VERSION,object_id:objectId,algorithm:ALG,dek_base64:key.toString('base64')})}catch(e){key.fill(0);throw e}const iv=randomBytes(IV_BYTES),cipher=createCipheriv('aes-256-gcm',key,iv,{authTagLength:TAG_BYTES});cipher.setAAD(aad(objectId));key.fill(0);const hash=createHash('sha256'),hasher=new Transform({transform(chunk,_e,cb){hash.update(chunk);cb(null,chunk)}}),out=new PassThrough(),source=Readable.fromWeb(plaintext as never);const completion=pipeline(source,hasher,cipher,out).then(()=>({plaintextSha256:hash.digest('hex'),authTagBase64:cipher.getAuthTag().toString('base64')})).catch(e=>{throw new StorageObjectCryptoError('STORAGE_ENCRYPT_STREAM_FAILED',e instanceof Error?e.message:'Storage encryption stream failed.')});return{stream:Readable.toWeb(out) as ReadableStream<Uint8Array>,metadata:{encryptionProfile:ALG,wrappedDek,contentIvBase64:iv.toString('base64')},completion}}
type WrappedDek={version:number;object_id:string;algorithm:string;dek_base64:string};
export async function decryptStorageObjectToFile(input:{objectId:string;encryptedBody:ReadableStream<Uint8Array>;outputPath:string;wrappedDek:VaultEnvelope;contentIvBase64:string;authTagBase64:string;expectedSha256:string;expectedPlaintextBytes:number;vault:StorageVaultLike}){const objectId=requireId(input.objectId),p=await input.vault.unsealJson<WrappedDek>(input.wrappedDek);if(p.version!==WRAP_VERSION||p.object_id!==objectId||p.algorithm!==ALG)throw new StorageObjectCryptoError('STORAGE_WRAPPED_DEK_BINDING_MISMATCH','Wrapped DEK does not match Storage Object.');const key=b64(p.dek_base64,KEY_BYTES,'STORAGE_WRAPPED_DEK_INVALID'),iv=b64(input.contentIvBase64,IV_BYTES,'STORAGE_CONTENT_IV_INVALID'),tag=b64(input.authTagBase64,TAG_BYTES,'STORAGE_AUTH_TAG_INVALID'),decipher=createDecipheriv('aes-256-gcm',key,iv,{authTagLength:TAG_BYTES});key.fill(0);iv.fill(0);decipher.setAAD(aad(objectId));decipher.setAuthTag(tag);tag.fill(0);const hash=createHash('sha256');let bytes=0;const hasher=new Transform({transform(chunk,_e,cb){bytes+=Buffer.byteLength(chunk);hash.update(chunk);cb(null,chunk)}});try{await pipeline(Readable.fromWeb(input.encryptedBody as never),decipher,hasher,createWriteStream(input.outputPath,{flags:'wx',mode:0o600}))}catch(e){await rm(input.outputPath,{force:true}).catch(()=>undefined);throw new StorageObjectCryptoError('STORAGE_GCM_AUTH_FAILED',e instanceof Error?e.message:'Storage object authentication failed.')}const sha=hash.digest('hex');if(bytes!==input.expectedPlaintextBytes){await rm(input.outputPath,{force:true}).catch(()=>undefined);throw new StorageObjectCryptoError('STORAGE_PLAINTEXT_SIZE_MISMATCH','Decrypted size does not match metadata.')}if(!hexEq(sha,input.expectedSha256)){await rm(input.outputPath,{force:true}).catch(()=>undefined);throw new StorageObjectCryptoError('STORAGE_SHA256_MISMATCH','Decrypted checksum does not match metadata.')}return{plaintextSha256:sha,plaintextBytes:bytes}}
export const storageObjectCryptoContract=Object.freeze({algorithm:ALG,dekBytes:KEY_BYTES,ivBytes:IV_BYTES,authTagBytes:TAG_BYTES,aadVersion:AAD_VERSION});
