name = "astera-billing-projection-staging"
main = "src/index.ts"
compatibility_date = "2025-09-17"

[[d1_databases]]
binding = "ASTERA_DB"
database_name = "astera-app-staging"
database_id = "08a705ac-50f4-4592-b726-d50154a2a8cb"
