export const PLAN_CREDIT_TEXT = {
  ja: {
    pageTitle: 'プラン / クレジット',
    planSectionTitle: 'プラン',
    creditSectionTitle: '追加クレジット',
    storageSectionTitle: 'ストレージ',
    plans: [
      { name: 'Free', features: ['基本処理'] },
      { name: 'Basic', features: ['基本処理', '高精度翻訳', '高精度文書作成', 'Private Mode', '外部ストレージ転送', 'Astera Storage'] },
      { name: 'Pro', features: ['Basicの全機能', '書類テンプレート', 'API'] },
      { name: 'Business', features: ['Proの全機能', '上位利用枠'] },
      { name: 'Enterprise', features: ['最大利用枠'] },
    ],
    credits: [
      { name: 'Credit Pack 1' },
      { name: 'Credit Pack 2' },
      { name: 'Credit Pack 3' },
      { name: 'Credit Pack 4' },
      { name: 'Credit Pack 5' },
    ],
    storage: [
      { name: 'Free' },
      { name: 'Small' },
      { name: 'Standard' },
      { name: 'Pro' },
      { name: 'Enterprise' },
    ],
  },
  en: {
    pageTitle: 'Plan / Credit',
    planSectionTitle: 'Plans',
    creditSectionTitle: 'Additional Credit',
    storageSectionTitle: 'Storage',
    plans: [
      { name: 'Free', features: ['Core processing'] },
      { name: 'Basic', features: ['Core processing', 'High-accuracy translation', 'High-accuracy document creation', 'Private Mode', 'External storage transfer', 'Astera Storage'] },
      { name: 'Pro', features: ['All Basic features', 'Document templates', 'API'] },
      { name: 'Business', features: ['All Pro features', 'Higher usage limits'] },
      { name: 'Enterprise', features: ['Maximum usage limits'] },
    ],
    credits: [
      { name: 'Credit Pack 1' },
      { name: 'Credit Pack 2' },
      { name: 'Credit Pack 3' },
      { name: 'Credit Pack 4' },
      { name: 'Credit Pack 5' },
    ],
    storage: [
      { name: 'Free' },
      { name: 'Small' },
      { name: 'Standard' },
      { name: 'Pro' },
      { name: 'Enterprise' },
    ],
  },
} as const;
