export const PLAN_CREDIT_TEXT = {
  ja: {
    pageTitle: 'プラン / クレジット',
    planSectionTitle: 'プラン',
    creditSectionTitle: '追加クレジット',
    storageSectionTitle: 'ストレージ',
    monthlyCredit: '月次Credit',
    grantedCredit: '付与Credit',
    includedFeatures: '利用できる機能',
    currentPlan: '現在のプラン',
    recommended: 'おすすめ',
    loadingCatalog: '料金情報を読み込んでいます…',
    catalogError: '料金情報を取得できませんでした。',
    storageTiers: ['Free', 'Small', 'Standard', 'Pro', 'Enterprise'],
    featureLabels: {
      basic_processing: '基本処理',
      core_processing: '基本処理',
      high_accuracy_translation: '高精度翻訳',
      translation: '高精度翻訳',
      high_accuracy_document_creation: '高精度文書作成',
      document_creation: '高精度文書作成',
      private_mode: 'Private Mode',
      external_storage_transfer: '外部ストレージ転送',
      astera_storage: 'Astera Storage',
      document_template: '書類テンプレート',
      document_templates: '書類テンプレート',
      api: 'API',
      developer_api: 'API',
      higher_usage_limits: '上位利用枠',
      maximum_usage_limits: '最大利用枠',
    },
    planFeatureFallbacks: {
      free: ['基本処理'],
      basic: ['基本処理', '高精度翻訳', '高精度文書作成', 'Private Mode', '外部ストレージ転送', 'Astera Storage'],
      pro: ['基本処理', '高精度翻訳', '高精度文書作成', 'Private Mode', '外部ストレージ転送', 'Astera Storage', '書類テンプレート', 'API'],
      business: ['基本処理', '高精度翻訳', '高精度文書作成', 'Private Mode', '外部ストレージ転送', 'Astera Storage', '書類テンプレート', 'API', '上位利用枠'],
      enterprise: ['基本処理', '高精度翻訳', '高精度文書作成', 'Private Mode', '外部ストレージ転送', 'Astera Storage', '書類テンプレート', 'API', '最大利用枠'],
    },
  },
  en: {
    pageTitle: 'Plan / Credit',
    planSectionTitle: 'Plans',
    creditSectionTitle: 'Additional Credit',
    storageSectionTitle: 'Storage',
    monthlyCredit: 'Monthly credit',
    grantedCredit: 'Granted credit',
    includedFeatures: 'Included features',
    currentPlan: 'Current plan',
    recommended: 'Recommended',
    loadingCatalog: 'Loading pricing…',
    catalogError: 'Pricing information is unavailable.',
    storageTiers: ['Free', 'Small', 'Standard', 'Pro', 'Enterprise'],
    featureLabels: {
      basic_processing: 'Core processing',
      core_processing: 'Core processing',
      high_accuracy_translation: 'High-accuracy translation',
      translation: 'High-accuracy translation',
      high_accuracy_document_creation: 'High-accuracy document creation',
      document_creation: 'High-accuracy document creation',
      private_mode: 'Private Mode',
      external_storage_transfer: 'External storage transfer',
      astera_storage: 'Astera Storage',
      document_template: 'Document templates',
      document_templates: 'Document templates',
      api: 'API',
      developer_api: 'API',
      higher_usage_limits: 'Higher usage limits',
      maximum_usage_limits: 'Maximum usage limits',
    },
    planFeatureFallbacks: {
      free: ['Core processing'],
      basic: ['Core processing', 'High-accuracy translation', 'High-accuracy document creation', 'Private Mode', 'External storage transfer', 'Astera Storage'],
      pro: ['Core processing', 'High-accuracy translation', 'High-accuracy document creation', 'Private Mode', 'External storage transfer', 'Astera Storage', 'Document templates', 'API'],
      business: ['Core processing', 'High-accuracy translation', 'High-accuracy document creation', 'Private Mode', 'External storage transfer', 'Astera Storage', 'Document templates', 'API', 'Higher usage limits'],
      enterprise: ['Core processing', 'High-accuracy translation', 'High-accuracy document creation', 'Private Mode', 'External storage transfer', 'Astera Storage', 'Document templates', 'API', 'Maximum usage limits'],
    },
  },
} as const;
