export const PLAN_CREDIT_TEXT = {
  ja: {
    pageTitle: 'プラン / クレジット',
    planSectionTitle: 'プラン',
    creditSectionTitle: '追加クレジット',
    storageSectionTitle: 'ストレージ',
    monthlyCredit: '月次Credit',
    grantedCredit: '付与Credit',
    includedFeatures: '利用できる機能',
    plans: [
      {
        name: 'Free',
        price: '¥0 / 月',
        creditValue: '初回 20,000 C / 以後 10,000 C',
        features: ['基本処理'],
      },
      {
        name: 'Basic',
        price: '¥980 / 月',
        creditValue: '180,000 C',
        features: ['基本処理', '高精度翻訳', '高精度文書作成', 'Private Mode', '外部ストレージ転送', 'Astera Storage'],
      },
      {
        name: 'Pro',
        price: '¥2,980 / 月',
        creditValue: '640,000 C',
        features: ['基本処理', '高精度翻訳', '高精度文書作成', 'Private Mode', '外部ストレージ転送', 'Astera Storage', '書類テンプレート', 'API'],
      },
      {
        name: 'Business',
        price: '¥9,980 / 月',
        creditValue: '2,200,000 C',
        features: ['基本処理', '高精度翻訳', '高精度文書作成', 'Private Mode', '外部ストレージ転送', 'Astera Storage', '書類テンプレート', 'API', '上位利用枠'],
      },
      {
        name: 'Enterprise',
        price: '¥29,800 / 月',
        creditValue: '6,600,000 C',
        features: ['基本処理', '高精度翻訳', '高精度文書作成', 'Private Mode', '外部ストレージ転送', 'Astera Storage', '書類テンプレート', 'API', '最大利用枠'],
      },
    ],
    credits: [
      { name: 'Credit Pack 1', price: '¥500', creditValue: '75,000 C' },
      { name: 'Credit Pack 2', price: '¥1,000', creditValue: '155,000 C' },
      { name: 'Credit Pack 3', price: '¥3,000', creditValue: '480,000 C' },
      { name: 'Credit Pack 4', price: '¥10,000', creditValue: '1,650,000 C' },
      { name: 'Credit Pack 5', price: '¥30,000', creditValue: '5,000,000 C' },
    ],
    storage: [
      { name: 'Free' },
      { name: 'Small' },
      { name: 'Standard' },
      { name: 'Pro' },
      { name: 'Enterprise' },
    ],
  },
  en: {
    pageTitle: 'Plan / Credit',
    planSectionTitle: 'Plans',
    creditSectionTitle: 'Additional Credit',
    storageSectionTitle: 'Storage',
    monthlyCredit: 'Monthly credit',
    grantedCredit: 'Granted credit',
    includedFeatures: 'Included features',
    plans: [
      {
        name: 'Free',
        price: '¥0 / month',
        creditValue: '20,000 C first month / 10,000 C after',
        features: ['Core processing'],
      },
      {
        name: 'Basic',
        price: '¥980 / month',
        creditValue: '180,000 C',
        features: ['Core processing', 'High-accuracy translation', 'High-accuracy document creation', 'Private Mode', 'External storage transfer', 'Astera Storage'],
      },
      {
        name: 'Pro',
        price: '¥2,980 / month',
        creditValue: '640,000 C',
        features: ['Core processing', 'High-accuracy translation', 'High-accuracy document creation', 'Private Mode', 'External storage transfer', 'Astera Storage', 'Document templates', 'API'],
      },
      {
        name: 'Business',
        price: '¥9,980 / month',
        creditValue: '2,200,000 C',
        features: ['Core processing', 'High-accuracy translation', 'High-accuracy document creation', 'Private Mode', 'External storage transfer', 'Astera Storage', 'Document templates', 'API', 'Higher usage limits'],
      },
      {
        name: 'Enterprise',
        price: '¥29,800 / month',
        creditValue: '6,600,000 C',
        features: ['Core processing', 'High-accuracy translation', 'High-accuracy document creation', 'Private Mode', 'External storage transfer', 'Astera Storage', 'Document templates', 'API', 'Maximum usage limits'],
      },
    ],
    credits: [
      { name: 'Credit Pack 1', price: '¥500', creditValue: '75,000 C' },
      { name: 'Credit Pack 2', price: '¥1,000', creditValue: '155,000 C' },
      { name: 'Credit Pack 3', price: '¥3,000', creditValue: '480,000 C' },
      { name: 'Credit Pack 4', price: '¥10,000', creditValue: '1,650,000 C' },
      { name: 'Credit Pack 5', price: '¥30,000', creditValue: '5,000,000 C' },
    ],
    storage: [
      { name: 'Free' },
      { name: 'Small' },
      { name: 'Standard' },
      { name: 'Pro' },
      { name: 'Enterprise' },
    ],
  },
} as const;
