import { useCallback } from 'react';
import { useTranslation } from 'react-i18next';

export const APP_TEXT = {
  ja: {
    navNew: '新しいページ', navSearch: '検索', navProjects: 'プロジェクト', navOptions: 'オプション', navPlanCredit: 'プラン / クレジット', navDeveloper: '開発者モード', navHistory: '履歴', navAbout: 'ASTERAとは？', navSettings: '設定',
    recent: '最近の履歴', recentLoading: '読み込み中…', recentEmpty: 'まだ履歴がありません', openHistory: '履歴を開く', openMenu: 'メニューを開く', closeMenu: 'メニューを閉じる', account: 'アカウント', openGuideAi: 'Astera案内AIを開く',
    settingsTitle: '設定', settingsDescription: '必要な設定だけを分けて管理します。', accountTitle: 'アカウント', accountDescription: '登録情報とGoogle / GitHubのログイン連携、ログアウト、アカウント管理。', securityTitle: 'セキュリティ', securityDescription: 'Password、Passkey、2段階認証、Backup Code、Session管理。', languageTitle: '言語', languageDescription: 'Astera Appで使用する表示言語だけを設定します。', notificationsTitle: '通知', notificationsDescription: 'Credit枯渇・購入・Update・重要なお知らせだけを管理します。', privacyTitle: 'プライバシー・データ', privacyDescription: '保存、Export、削除、Data Rightsを管理します。', legalSupportTitle: '法務・サポート', legalSupportDescription: '利用規約、Privacy Policy、特定商取引法表記、問い合わせ、Help。',
    languageSelect: '表示言語', japanese: '日本語', english: 'English', saved: '保存しました。', save: '保存',
    notificationCredit: 'Credit通知', notificationSystem: 'Asteraからのお知らせ', creditLow: 'Credit残量低下', creditCritical: 'Credit残量が危険域', creditInsufficient: 'Credit不足', creditPurchasePending: '購入処理中', creditCredited: 'Credit反映完了', creditResume: '実行再開可能', updateNotice: 'Astera Update', importantNotice: '重要なお知らせ', notificationChannel: '通知方法', appNotice: 'App内通知', emailNotice: 'Email通知', pushNotice: 'Push通知',
    legalTerms: '利用規約', legalPrivacy: 'プライバシーポリシー', legalCommerce: '特定商取引法表記', contact: '問い合わせ', help: 'Help / FAQ',
    searchTitle: '検索', searchDescription: '保存済みの履歴・Resultを検索します。', searchKeyword: 'キーワード', searchButton: '検索', planCreditTitle: 'プラン / クレジット', planCreditDescription: '契約PlanとCredit残高・購入を一つの入口から確認します。', planLink: 'プランを確認', creditLink: 'クレジットを確認・追加',
    developerVault: 'Libral Vault API', developerVaultDescription: '暗号化、Vault操作、鍵管理、Permission、Usage / LogをDeveloper Modeから管理します。', developerApi: 'Astera API / API Key', developerWebhook: 'Webhook', developerDocs: 'Developer Documentation', developerAvailable: '利用可能', developerUnavailable: 'Catalog未登録',
    loginConnections: 'ログイン連携', google: 'Google', github: 'GitHub', connected: '連携済み', notConnected: '未連携', link: '連携する', unlink: '連携解除', logout: 'ログアウト', accountDanger: 'アカウント管理', deleteAccount: 'アカウント削除', manageSecurity: 'セキュリティ設定を開く',

    optionPageDescription: 'Composerの「＋／@」へ表示する4実行Option候補と、独立機能の管理導線を設定します。', optionExecutionCandidates: '実行Option候補', optionTranslation: '高精度翻訳', optionTranslationDescription: '本文を翻訳する実行Optionです。要約・改善・校正・再構成は追加せず、翻訳先はComposerの「@」から選びます。', optionAgentMode: 'Agent Mode', optionAgentModeDescription: '実行ごとにエージェント低／中／高を選ぶModeです。設定Toggleは候補表示だけを制御します。', optionDocument: '書類作成', optionDocumentDescription: 'Google Sheets固定書式を対象に、Astera公式Template／個別Templateを「@」から選びます。', optionStorageTransfer: '外部Storage転送', optionStorageTransferDescription: '接続済みの利用者Storageへ成果物を転送します。Destinationは「@」から選びます。', optionInfoAriaSuffix: 'の説明', optionSourceUnavailable: '現在設定を取得できていないため上書きを停止しました。', optionSaved: 'Option候補表示を保存しました。', optionToggleNote: 'このToggleは候補へ表示する／しないだけを制御します。ここで実行・課金は行いません。', optionIndependentFeatures: '独立機能', optionPrivateMode: 'Private Mode', optionPrivateModeDescription: 'Composerを開くたび既定ONです。恒久OFF設定は設けません。本文・File・中間物・ResultをAstera側へ永続保存しません。', optionManageInComposer: 'Composerで管理 ›', optionAsteraStorage: 'Astera Storage', optionAsteraStorageDescription: '容量・Object・Grace等を管理', optionOpenSettings: '設定を開く ›', optionVaultProtection: '暗号化・鍵管理（Libral Vault）', optionVaultProtectionDescription: 'HTTPS/TLSと内部Secret保護を含む暗号化境界は常時有効です。暗号化OFF Toggleは作りません。', optionAlwaysProtected: '常時保護',

    securityPageDescription: 'Passkey、2FA、Backup Code、現在Sessionを実際の認証Runtimeで管理します。', securityLoading: 'Security状態を確認しています…', securityWorking: '処理しています…', securityPasskey: 'Passkey', securityPasskeyDefaultName: 'Passkey', securityUnknownDevice: 'unknown', securityPasskeyDescription: '端末の生体認証、PIN、Security Keyを利用できます。', securityCountSuffix: '件', securityDisplayNameOptional: '表示名（任意）', securityDisplayNamePlaceholder: '例: Pixel Passkey', securityAddThisDevice: 'この端末へ追加', securityNoPasskeys: '登録済みPasskeyはありません。', securitySynced: '同期済み', securityDeviceStored: '端末保存', securityDelete: '削除', securityTwoFactor: '2段階認証', securityTwoFactorDescription: 'AuthenticatorのTOTPと一度だけ使えるBackup Codeを使用します。', securityEnabled: '有効', securityDisabled: '無効', securityCurrentPassword: '現在のPassword', securityStartTwoFactor: '2FA設定を開始', securityAuthenticatorEnrollment: 'Authenticator登録', securityAuthenticatorInstruction: '次の`otpauth://` URIをAuthenticatorへ登録し、6桁Codeを入力してください。', securityCopyUri: 'URIをコピー', securitySixDigitCode: '6桁Code', securityVerifyEnable: '確認して有効化', securityBackupPassword: 'Backup Code再発行用Password', securityRegenerateBackup: 'Backup Codeを再発行', securityDisablePassword: '2FA無効化用Password', securityDisableTwoFactor: '2FAを無効化', securityBackupCodes: 'Backup Code', securityBackupCodesDescription: 'この表示を閉じると再表示しません。安全な場所へ保存してください。', securityCopyAll: '全てコピー', securityCloseAfterSave: '保存したので閉じる', securityCurrentSession: '現在Session', securityCurrentSessionDescription: 'Session IDは一部だけ表示し、Secret Tokenは表示しません。', securitySession: 'Session', securityExpiresAt: '有効期限', securityUnavailable: '取得不可',
    securityPasskeyListFailed: 'Passkey一覧を取得できませんでした。', securityPasskeyAddFailed: 'Passkeyを追加できませんでした。', securityPasskeyAdded: 'Passkeyを追加しました。', securityPasskeyDeleteFailed: 'Passkeyを削除できませんでした。', securityPasskeyDeleted: 'Passkeyを削除しました。', securityTwoFactorStartFailed: '2FAを開始できませんでした。', securityEnrollmentIncomplete: 'TOTP URIまたはBackup Codeを受信できませんでした。', securityAuthenticatorReady: 'Authenticatorへ登録し、表示されたCodeで確認してください。', securityTotpVerifyFailed: 'TOTP Codeを確認できませんでした。', securityTwoFactorEnabled: '2FAを有効化しました。Backup Codeを今すぐ安全な場所へ保存してください。', securityTwoFactorDisableFailed: '2FAを無効化できませんでした。', securityTwoFactorDisabled: '2FAを無効化しました。', securityBackupGenerateFailed: 'Backup Codeを再発行できませんでした。', securityBackupMissing: 'Backup Codeを受信できませんでした。', securityBackupRegenerated: '古いBackup Codeを無効化し、新しいCodeを発行しました。', securityClipboardFailed: 'Clipboardへコピーできませんでした。', securityTotpCopied: 'TOTP URIをコピーしました。', securityBackupCopied: 'Backup Codeをコピーしました。',
  },
  en: {
    navNew: 'New page', navSearch: 'Search', navProjects: 'Projects', navOptions: 'Options', navPlanCredit: 'Plan / Credits', navDeveloper: 'Developer Mode', navHistory: 'History', navAbout: 'What is ASTERA?', navSettings: 'Settings',
    recent: 'Recent', recentLoading: 'Loading…', recentEmpty: 'No history yet', openHistory: 'Open history', openMenu: 'Open menu', closeMenu: 'Close menu', account: 'Account', openGuideAi: 'Open Astera Guide AI',
    settingsTitle: 'Settings', settingsDescription: 'Manage each setting in a clear, separate area.', accountTitle: 'Account', accountDescription: 'Profile, Google / GitHub login links, logout, and account management.', securityTitle: 'Security', securityDescription: 'Password, passkey, two-factor authentication, backup codes, and sessions.', languageTitle: 'Language', languageDescription: 'Choose only the display language used by Astera App.', notificationsTitle: 'Notifications', notificationsDescription: 'Manage only credit, purchase, update, and important notices.', privacyTitle: 'Privacy & Data', privacyDescription: 'Manage storage, export, deletion, and data rights.', legalSupportTitle: 'Legal & Support', legalSupportDescription: 'Terms, Privacy Policy, commerce disclosure, contact, and help.',
    languageSelect: 'Display language', japanese: '日本語', english: 'English', saved: 'Saved.', save: 'Save',
    notificationCredit: 'Credit notifications', notificationSystem: 'Astera notices', creditLow: 'Low credit', creditCritical: 'Credit critical', creditInsufficient: 'Insufficient credit', creditPurchasePending: 'Purchase pending', creditCredited: 'Credits added', creditResume: 'Execution can resume', updateNotice: 'Astera Update', importantNotice: 'Important notice', notificationChannel: 'Channels', appNotice: 'In-app', emailNotice: 'Email', pushNotice: 'Push',
    legalTerms: 'Terms of Service', legalPrivacy: 'Privacy Policy', legalCommerce: 'Commerce disclosure', contact: 'Contact', help: 'Help / FAQ',
    searchTitle: 'Search', searchDescription: 'Search saved history and results.', searchKeyword: 'Keyword', searchButton: 'Search', planCreditTitle: 'Plan / Credits', planCreditDescription: 'Review your plan and credit balance or purchases from one place.', planLink: 'View plan', creditLink: 'View / add credits',
    developerVault: 'Libral Vault API', developerVaultDescription: 'Manage encryption, vault operations, keys, permissions, usage, and logs from Developer Mode.', developerApi: 'Astera API / API Keys', developerWebhook: 'Webhooks', developerDocs: 'Developer Documentation', developerAvailable: 'Available', developerUnavailable: 'Not in catalog',
    loginConnections: 'Login connections', google: 'Google', github: 'GitHub', connected: 'Connected', notConnected: 'Not connected', link: 'Connect', unlink: 'Disconnect', logout: 'Log out', accountDanger: 'Account management', deleteAccount: 'Delete account', manageSecurity: 'Open security settings',

    optionPageDescription: 'Configure the four execution-option candidates shown in Composer “+ / @” and the entry points for independent features.', optionExecutionCandidates: 'Execution option candidates', optionTranslation: 'High-accuracy translation', optionTranslationDescription: 'Translates the body text only. It does not add summarization, improvement, proofreading, or restructuring; choose the target language from Composer “@”.', optionAgentMode: 'Agent Mode', optionAgentModeDescription: 'Select low / medium / high agent execution for each run. This settings toggle only controls whether the candidate is shown.', optionDocument: 'Document creation', optionDocumentDescription: 'Uses fixed-format Google Sheets and lets you select Astera official or personal templates from “@”.', optionStorageTransfer: 'External storage transfer', optionStorageTransferDescription: 'Transfers output to a connected user storage destination selected from “@”.', optionInfoAriaSuffix: ' description', optionSourceUnavailable: 'Current preferences could not be loaded, so overwrite has been stopped.', optionSaved: 'Option candidate visibility was saved.', optionToggleNote: 'These toggles only control whether candidates are shown. They do not execute anything or charge credits here.', optionIndependentFeatures: 'Independent features', optionPrivateMode: 'Private Mode', optionPrivateModeDescription: 'Defaults to ON whenever Composer opens. There is no permanent OFF setting. Body text, files, intermediate data, and results are not persistently stored by Astera.', optionManageInComposer: 'Manage in Composer ›', optionAsteraStorage: 'Astera Storage', optionAsteraStorageDescription: 'Manage capacity, objects, grace state, and related storage status', optionOpenSettings: 'Open settings ›', optionVaultProtection: 'Encryption & key management (Libral Vault)', optionVaultProtectionDescription: 'Encryption boundaries including HTTPS/TLS and internal secret protection are always enabled. No encryption-OFF toggle is provided.', optionAlwaysProtected: 'Always protected',

    securityPageDescription: 'Manage passkeys, 2FA, backup codes, and the current session through the actual authentication runtime.', securityLoading: 'Checking security status…', securityWorking: 'Processing…', securityPasskey: 'Passkey', securityPasskeyDefaultName: 'Passkey', securityUnknownDevice: 'unknown', securityPasskeyDescription: 'Use device biometrics, PIN, or a security key.', securityCountSuffix: ' items', securityDisplayNameOptional: 'Display name (optional)', securityDisplayNamePlaceholder: 'e.g. Pixel Passkey', securityAddThisDevice: 'Add to this device', securityNoPasskeys: 'No passkeys are registered.', securitySynced: 'Synced', securityDeviceStored: 'Stored on device', securityDelete: 'Delete', securityTwoFactor: 'Two-factor authentication', securityTwoFactorDescription: 'Use authenticator TOTP and one-time backup codes.', securityEnabled: 'Enabled', securityDisabled: 'Disabled', securityCurrentPassword: 'Current password', securityStartTwoFactor: 'Start 2FA setup', securityAuthenticatorEnrollment: 'Authenticator setup', securityAuthenticatorInstruction: 'Register the following `otpauth://` URI in your authenticator, then enter the 6-digit code.', securityCopyUri: 'Copy URI', securitySixDigitCode: '6-digit code', securityVerifyEnable: 'Verify and enable', securityBackupPassword: 'Password to regenerate backup codes', securityRegenerateBackup: 'Regenerate backup codes', securityDisablePassword: 'Password to disable 2FA', securityDisableTwoFactor: 'Disable 2FA', securityBackupCodes: 'Backup codes', securityBackupCodesDescription: 'These codes will not be shown again after this view is closed. Store them securely now.', securityCopyAll: 'Copy all', securityCloseAfterSave: 'I saved them — close', securityCurrentSession: 'Current session', securityCurrentSessionDescription: 'Only part of the session ID is shown; secret tokens are never displayed.', securitySession: 'Session', securityExpiresAt: 'Expires', securityUnavailable: 'Unavailable',
    securityPasskeyListFailed: 'Could not load the passkey list.', securityPasskeyAddFailed: 'Could not add the passkey.', securityPasskeyAdded: 'Passkey added.', securityPasskeyDeleteFailed: 'Could not delete the passkey.', securityPasskeyDeleted: 'Passkey deleted.', securityTwoFactorStartFailed: 'Could not start 2FA setup.', securityEnrollmentIncomplete: 'TOTP URI or backup codes were not received.', securityAuthenticatorReady: 'Register it in your authenticator and verify with the displayed code.', securityTotpVerifyFailed: 'Could not verify the TOTP code.', securityTwoFactorEnabled: '2FA is enabled. Save the backup codes somewhere secure now.', securityTwoFactorDisableFailed: 'Could not disable 2FA.', securityTwoFactorDisabled: '2FA disabled.', securityBackupGenerateFailed: 'Could not regenerate backup codes.', securityBackupMissing: 'Backup codes were not received.', securityBackupRegenerated: 'Old backup codes were revoked and new codes were generated.', securityClipboardFailed: 'Could not copy to the clipboard.', securityTotpCopied: 'TOTP URI copied.', securityBackupCopied: 'Backup codes copied.',
  },
} as const;

export type AppTextKey = keyof typeof APP_TEXT.ja;

export function useAppText() {
  const { i18n } = useTranslation();
  const language: 'en' | 'ja' = i18n.resolvedLanguage?.toLowerCase().startsWith('en') ? 'en' : 'ja';
  const text = useCallback((key: AppTextKey) => APP_TEXT[language][key], [language]);
  const setLanguage = useCallback(async (next: 'ja' | 'en') => {
    localStorage.setItem('astera-language', next);
    document.documentElement.lang = next;
    await i18n.changeLanguage(next);
  }, [i18n]);
  return { language, text, setLanguage };
}
