import { useEffect, useState, type ReactNode } from 'react';
import { createPortal } from 'react-dom';
import './canonical-settings-exterior.css';

type Fact = readonly [string, string];
type Surface = { title: string; subtitle: string; states?: readonly string[]; facts?: readonly Fact[]; actions?: readonly string[]; children?: ReactNode };

const routeKey = () => window.location.pathname.replace(/\/+$/, '') || '/';
const findHost = () => document.querySelector<HTMLElement>('.platform-page-content') ?? document.querySelector<HTMLElement>('.platform-main') ?? document.querySelector<HTMLElement>('main');

function Chips({ items }: { items: readonly string[] }) { return <div className="exterior-canon-chips">{items.map((item) => <span key={item}>{item}</span>)}</div>; }
function Facts({ items }: { items: readonly Fact[] }) { return <div className="exterior-canon-grid">{items.map(([label, value]) => <div className="exterior-canon-fact" key={label}><small>{label}</small><strong>{value}</strong></div>)}</div>; }
function Actions({ items }: { items: readonly string[] }) { return <div className="exterior-canon-actions">{items.map((item) => <button key={item} type="button" disabled aria-disabled="true">{item}</button>)}</div>; }
function Section({ surface }: { surface: Surface }) { return <section className="exterior-canon-section" data-react-canonical-exterior="true"><header><div><h2>{surface.title}</h2><p>{surface.subtitle}</p></div></header>{surface.states?.length ? <Chips items={surface.states} /> : null}{surface.facts?.length ? <Facts items={surface.facts} /> : null}{surface.actions?.length ? <Actions items={surface.actions} /> : null}{surface.children}</section>; }

function routeSurface(route: string): Surface | null {
  if (route === '/app/settings') return { title: 'Settings状態', subtitle: '全Categoryで共通に扱う画面状態', states: ['Loading','Ready','Locked','Permission Required','Maintenance','Error'], facts: [['Locked表示','理由＋必要Plan'],['Permission','必要権限を明示'],['Desktop','Overlay / Panel'],['Mobile','全画面List']] };
  if (route === '/app/settings/options') return { title: 'Option設定 状態', subtitle: 'Toggleは候補表示だけを制御し、自動実行・課金しない', states: ['Saving','Saved','Plan Locked','Provider Unavailable','Error'], facts: [['高精度翻訳','候補表示Toggle'],['Agent Mode','候補表示Toggle'],['書類作成','候補表示Toggle'],['外部Storage転送','候補表示Toggle']] };
  if (route === '/app/settings/language') return { title: '表示・言語 詳細', subtitle: '表示、言語、根拠表示、Motion、Locale状態', states: ['Loading','Saving','Saved','Unsupported Locale','Error'], facts: [['System言語',document.documentElement.lang||'ja-JP'],['Theme',document.documentElement.dataset.theme||'System'],['根拠表示方式','—'],['Reduced Motion','Preference'],['HTML lang',document.documentElement.lang||'—'],['Direction / RTL',document.documentElement.dir||'LTR'],['Locale Support','Catalogで判定'],['Focus保持','言語変更後も維持']] };
  if (route === '/app/settings/templates') return { title: 'Template管理', subtitle: '作成後の検査・Preview・Version・Lifecycleまで含む外装', states: ['Draft','Validating','Ready','Warning','Rejected','Disabled','Deleted'], facts: [['Google接続','未接続 / 接続状態'],['Template検査','状態・警告を表示'],['Preview','差分確認面'],['Version','現在Version / 履歴'],['原本変更','Diff Gateで確認'],['権限','Provider権限状態'],['名称','選択Template'],['有効状態','Enabled / Disabled']], actions: ['Googleへ接続','検査','Preview','名称変更','複製','有効/無効','Version履歴','削除'] };
  if (route === '/app/settings/storage-destinations') return { title: '外部Storage 接続詳細', subtitle: 'Destinationごとの認証・Scope・Root・接続Test・Revoke外装', states: ['Connected','Needs Reauth','Scope Changed','Unavailable','Revoked','Error'], facts: [['Provider','—'],['Scope','—'],['Root Folder','—'],['接続Test','—'],['最終利用日時','—'],['Credential','Vault Referenceのみ'],['OAuth状態','—'],['登録数','任意上限なし']], actions: ['追加','再認証','Scope確認','Root Folder変更','接続Test','削除'] };
  if (route === '/app/settings/astera-storage') return { title: 'Astera Storage 詳細', subtitle: '容量・Quota・Grace・保存停止・Object Lifecycle外装', states: ['Active','Near Limit','Over Limit','Grace','Read Only','Deletion Scheduled','Unavailable'], facts: [['契約容量','—'],['使用量','—'],['予約量','—'],['残量','—'],['次回Credit減算','—'],['Grace','—'],['保存停止','—'],['削除予定','—'],['暗号化','—'],['Private Mode','保存対象外'],['Object数','—'],['容量変更','—']], actions: ['容量変更','File一覧','Download','Delete','Restore Request'] };
  if (route === '/app/settings/data-privacy') return { title: 'Data Rights 状態', subtitle: 'Export・削除・再認証を含む状態外装', states: ['Ready','Export Preparing','Export Ready','Deletion Scheduled','Legal Hold','Error'], facts: [['Private Mode','永続保存しない'],['Normal Mode','保存設定に従う'],['Data Export','状態・取得導線'],['削除Request','状態・取消導線'],['保持期間','—'],['外部Provider送信','—'],['同意Version','—'],['Fresh Session','重要操作で必要'],['Cookie / 認証技術','説明表示'],['Legal Hold','法定保持と本文削除を分離']], actions: ['Data Export','Exportを取得','Account削除Request','削除Request取消'] };
  if (route === '/app/settings/notifications') return { title: '通知・Credit警告 詳細', subtitle: 'Channel、Event、Quiet Hours、権限、Deep Link', states: ['credit.low','credit.critical','credit.insufficient','credit.purchase_pending','credit.credited','credit.resume_available','credit.resume_blocked'], facts: [['App内通知','必須 / 無効化不可'],['Email','任意 ON / OFF'],['Push','任意 ON / OFF'],['端末Permission','—'],['低残高Policy','Version付きCatalog'],['Quiet Hours','低残高通知だけ対象'],['Billing権限','購入Action表示を分離'],['Dedupe','同一状態の重複禁止'],['通知表示','Icon / 見出し / 状態文'],['Credit情報','残高 / 必要量'],['Action','状態別Action'],['発生日時','Timestamp'],['Deep Link','Return Context付き'],['Screen Reader','Live Region'],['Mobile','Bottom Sheet対応'],['Privacy','Prompt / File名 / Secretを含めない']] };
  if (route === '/account/security') return { title: 'Account・Security 詳細', subtitle: 'Login手段、Session、Security Eventまで含む外装', states: ['Fresh Auth Required','2FA Setup','Recovery Codes Shown','Session Revoked','Provider Error'], facts: [['Password変更','Fresh Session'],['Passkey','一覧 / 名称 / 削除'],['TOTP','設定 / 状態'],['Backup Code','再生成 / 1回表示'],['OAuth Identity','Link / Unlink'],['Session','一覧 / 個別失効 / 全失効'],['Security Event','履歴表示'],['最後のLogin手段','削除禁止']], actions: ['Password変更','Passkey管理','TOTP設定','Backup Code再生成','OAuth Link/Unlink','Session一覧','全Session失効','Security Event'] };
  if (route === '/account/subscription') return { title: 'Plan・Subscription 詳細', subtitle: '契約状態と変更・失敗・Graceを同一Surfaceで確認', states: ['Active','Pending Change','Past Due','Cancelled At Period End','Expired','Reconciliation'], facts: [['Current Plan','—'],['更新日','—'],['月次Credit','—'],['Payment状態','—'],['Grace','—'],['Downgrade影響','API / Storage / Private等'],['Catalog Version','—'],['Square管理','外部導線']], actions: ['Upgrade','Downgrade','解約','Square管理'] };
  if (route === '/account/credit') return { title: 'Credit 状態・Recovery', subtitle: '購入、Ledger、通常App復帰、Developer API復帰を分けて表示', states: ['Healthy','Low','Critical','Insufficient For Estimate','Depleted','Purchase Pending','Payment Confirmed / Credit Pending','Credited','App Resume Ready','API Resume Evaluating','API Auto Resumed','API Manual Resume Required','Reconciliation','Error'], facts: [['利用可能残高','—'],['予約残高','—'],['概算残り実行回数','—'],['固定Pack / 自由購入','Catalog'],['Ledger Filter','—'],['取引詳細','—'],['補填・返却','—'],['通知設定','—'],['通常App復帰待ち','—'],['停止Developer API Key数','—'],['不足量','—'],['Return Context','Surface / Return Path']], actions: ['Ledgerを絞り込む','取引詳細','元の入力へ戻る','必要量を減らす','停止中Keyを見る','通知設定'] };
  if (route === '/app/developer') return { title: 'Developer Mode 状態・Recovery', subtitle: 'Key Lifecycle、Credit停止、再開、削除確認までの外装', states: ['稼働中','Credit残量低下','Credit不足で停止中','補給確認中','補給済み・自動再開','補給済み・手動再開待ち','利用者が停止中','Plan変更で停止','Account停止','Security確認中','Target停止','削除済み'], facts: [['Login中Account','—'],['Tenant / Workspace','—'],['Current Plan','—'],['API Entitlement','—'],['利用可能Credit','—'],['予約中Credit','—'],['API全体状態','—'],['低残高警告','—'],['Key名 / Prefix','—'],['Target / Environment','—'],['Scope','—'],['主状態 / 全停止理由','—'],['Auto Resume','—'],['最終利用','—'],['今月Request / Credit','—'],['概算残りRequest','—'],['Status History','—'],['Usage / Credit内訳','—'],['Rate / Quota','—'],['OpenAPI / Code例','—']], actions: ['詳細','Rotate','停止','再開','削除','もう一度実行'], children: <><div className="exterior-canon-alert"><strong>Credit不足Banner</strong><p>新しいAPI実行を実行前に停止し、現在残高・必要予約量・停止日時・対象Tenant・Auto Resumeを表示する。</p><Actions items={['Creditを追加','停止中Keyを見る','状態を更新']} /></div><div className="exterior-canon-dialog-preview"><strong>削除前確認Dialog</strong><p>Key名・Prefix・Target・Environment・最終利用・削除後は復元できないことを表示。Production Keyは再認証が必要。</p><Actions items={['削除を確認','キャンセル']} /></div><div className="exterior-canon-dialog-preview"><strong>Pause / Resume</strong><p>Pause理由、予約済み実行の継続/Cancel、残存Holdと解消Actionを表示する。</p><Actions items={['Pause','予約済みを継続','予約済みをCancel','Resume']} /></div></> };
  return null;
}

export function CanonicalSettingsExterior() {
  const [state, setState] = useState(() => ({ route: routeKey(), host: findHost() }));
  useEffect(() => {
    const sync = () => setState((current) => { const next = { route: routeKey(), host: findHost() }; return current.route === next.route && current.host === next.host ? current : next; });
    const observer = new MutationObserver(sync); observer.observe(document.documentElement, { childList: true, subtree: true }); window.addEventListener('popstate', sync); sync();
    return () => { observer.disconnect(); window.removeEventListener('popstate', sync); };
  }, []);
  const surface = routeSurface(state.route);
  if (!surface || !state.host) return null;
  return createPortal(<Section surface={surface} />, state.host);
}
