import { useCallback, useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import { apiRequest, asArray, asRecord, recordText } from './api-client';
import './canonical-notification-management.css';

type Prefs={in_app_enabled:boolean;email_enabled:boolean;push_enabled:boolean;warning_policy_version:string;events:string[];quiet_hours_start:string;quiet_hours_end:string};
type Policy={version:string;low_threshold:number|null;critical_threshold:number|null};
type Feedback={type:'idle'|'working'|'success'|'error';message?:string};
const EVENT_LABELS:Record<string,string>={'credit.low':'残高低下','credit.critical':'枯渇が近い','credit.insufficient':'Credit不足停止','credit.purchase_pending':'支払確認中','credit.credited':'Credit反映完了','credit.resume_available':'再実行可能','credit.resume_blocked':'別Holdで停止継続'};
const routeKey=()=>window.location.pathname.replace(/\/+$/,'')||'/';
const findHost=()=>document.querySelector<HTMLElement>('.platform-page-content')??document.querySelector<HTMLElement>('.platform-main')??document.querySelector<HTMLElement>('main');

function Surface(){
 const[loading,setLoading]=useState(true);const[prefs,setPrefs]=useState<Prefs|null>(null);const[policy,setPolicy]=useState<Policy>({version:'',low_threshold:null,critical_threshold:null});const[supported,setSupported]=useState<string[]>([]);const[feedback,setFeedback]=useState<Feedback>({type:'idle'});
 const reload=useCallback(async()=>{setLoading(true);try{const payload=asRecord(await apiRequest('/api/credit/notification-preferences'));const p=asRecord(payload.preferences);const pol=asRecord(payload.policy);setPrefs({in_app_enabled:true,email_enabled:p.email_enabled===true,push_enabled:p.push_enabled===true,warning_policy_version:recordText(p,['warning_policy_version']),events:asArray(p.events).filter((v):v is string=>typeof v==='string'),quiet_hours_start:recordText(p,['quiet_hours_start']),quiet_hours_end:recordText(p,['quiet_hours_end'])});setPolicy({version:recordText(pol,['version']),low_threshold:typeof pol.low_threshold==='number'?pol.low_threshold:null,critical_threshold:typeof pol.critical_threshold==='number'?pol.critical_threshold:null});setSupported(asArray(payload.supported_events).filter((v):v is string=>typeof v==='string'));}catch(error){setFeedback({type:'error',message:error instanceof Error?error.message:'通知設定を取得できませんでした。'});}finally{setLoading(false);}},[]);
 useEffect(()=>{void reload();},[reload]);
 const save=async()=>{if(!prefs||feedback.type==='working')return;setFeedback({type:'working'});try{const payload=asRecord(await apiRequest('/api/credit/notification-preferences',{method:'PATCH',idempotent:true,body:{...prefs,in_app_enabled:true}}));const p=asRecord(payload.preferences);setPrefs({...prefs,email_enabled:p.email_enabled===true,push_enabled:p.push_enabled===true,warning_policy_version:recordText(p,['warning_policy_version']),events:asArray(p.events).filter((v):v is string=>typeof v==='string'),quiet_hours_start:recordText(p,['quiet_hours_start']),quiet_hours_end:recordText(p,['quiet_hours_end'])});setFeedback({type:'success',message:'通知・Credit警告設定を保存しました。'});}catch(error){setFeedback({type:'error',message:error instanceof Error?error.message:'設定を保存できませんでした。'});}};
 if(loading&&!prefs)return <section className="notification-management"><p>通知設定を読み込んでいます…</p></section>;
 if(!prefs)return <section className="notification-management"><button className="platform-button" type="button" onClick={()=>void reload()}>再取得</button>{feedback.message&&<p role="alert">{feedback.message}</p>}</section>;
 const toggleEvent=(event:string)=>setPrefs((current)=>current?{...current,events:current.events.includes(event)?current.events.filter((v)=>v!==event):[...current.events,event]}:current);
 return <section className="notification-management" data-canon-notification-management="true"><header><div><h2>通知・Credit警告</h2><p>閾値をFrontendへ固定せず、ServerのVersion付きCredit Policyを表示します。</p></div><button className="platform-button" type="button" onClick={()=>void reload()}>再読込</button></header>{feedback.type!=='idle'&&<div className={`notification-feedback is-${feedback.type}`} role={feedback.type==='error'?'alert':'status'}>{feedback.type==='working'?'保存しています…':feedback.message}</div>}<section className="notification-policy"><div><small>Policy Version</small><strong>{policy.version||'未設定'}</strong></div><div><small>Low</small><strong>{policy.low_threshold??'未設定'}</strong></div><div><small>Critical</small><strong>{policy.critical_threshold??'未設定'}</strong></div></section><section className="notification-card"><h3>Channel</h3><label className="notification-toggle"><span><strong>App内通知</strong><small>安全状態通知のため常時ON</small></span><input type="checkbox" checked disabled /></label><label className="notification-toggle"><span><strong>Email</strong><small>任意</small></span><input type="checkbox" checked={prefs.email_enabled} onChange={(e)=>setPrefs({...prefs,email_enabled:e.target.checked})}/></label><label className="notification-toggle"><span><strong>Push</strong><small>端末許可が無い場合はApp内へFallback</small></span><input type="checkbox" checked={prefs.push_enabled} onChange={(e)=>setPrefs({...prefs,push_enabled:e.target.checked})}/></label></section><section className="notification-card"><h3>任意Channelで通知するEvent</h3><div className="notification-events">{supported.map((event)=><label key={event}><input type="checkbox" checked={prefs.events.includes(event)} onChange={()=>toggleEvent(event)}/><span><strong>{EVENT_LABELS[event]||event}</strong><small>{event}</small></span></label>)}</div></section><section className="notification-card"><h3>Quiet Hours</h3><p>低残高／Criticalだけに適用します。Credit不足など停止通知は遅延させません。</p><div className="notification-times"><label><span>開始</span><input type="time" value={prefs.quiet_hours_start} onChange={(e)=>setPrefs({...prefs,quiet_hours_start:e.target.value})}/></label><label><span>終了</span><input type="time" value={prefs.quiet_hours_end} onChange={(e)=>setPrefs({...prefs,quiet_hours_end:e.target.value})}/></label></div></section><button className="platform-button is-primary" type="button" onClick={()=>void save()} disabled={feedback.type==='working'}>保存</button><section className="notification-card is-muted"><h3>Delivery実装状態</h3><p>Preference保存はD1へ接続します。Email／Push Provider配送、複数端末既読、Deep Link Delivery E2Eは別Runtime検証が必要です。</p></section></section>;
}
export function CanonicalNotificationManagement(){const[state,setState]=useState(()=>({route:routeKey(),host:findHost()}));useEffect(()=>{const sync=()=>setState((c)=>{const n={route:routeKey(),host:findHost()};return c.route===n.route&&c.host===n.host?c:n;});const o=new MutationObserver(sync);o.observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('popstate',sync);sync();return()=>{o.disconnect();window.removeEventListener('popstate',sync);};},[]);useEffect(()=>{document.documentElement.classList.toggle('notification-management-active',state.route==='/app/settings/notifications'&&Boolean(state.host));return()=>document.documentElement.classList.remove('notification-management-active');},[state]);if(state.route!=='/app/settings/notifications'||!state.host)return null;return createPortal(<Surface/>,state.host);}
